# Bifrosts are counted as 0 - 4 AS A BOT.
# Use 0 - 4 below Please!
characters = [
    {
        "index": 0,
        "class": "bard",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 4, # Check screenshots/Mokomoko_bifrost_start.png for starting location
    },
    {
        "index": 1,
        "class": "artillerist",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 3,
    },
    {
        "index": 2,
        "class": "summoner",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 4,
    },
    {
        "index": 3,
        "class": "arcana",
        "ilvl-endless": 1475,
        "ilvl-aor": 1475,
        "lopang": False,
        "leapstones": True,
        "guildDonation": False,
        "rapport": False,
        "mokomokoBifrost": 4,
    },
    {
        "index": 4,
        "class": "deadeye",
        "ilvl-endless": 1475,
        "ilvl-aor": 1475,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 3,
    },
    {
        "index": 5,
        "class": "artist",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": False,
        "leapstones": True,
        "guildDonation": False,
        "rapport": False,
        "mokomokoBifrost": 4,
    },
    {
        "index": 6,
        "class": "destroyer",
        "ilvl-endless": 1475,
        "ilvl-aor": 1475,
        "lopang": True,
        "leapstones": False,
        "guildDonation": False,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "machinist",
        "ilvl-endless": 1445,
        "ilvl-aor": 1445,
        "lopang": True,
        "leapstones": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 8,
        "class": "gunlancer",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "leapstones": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 9,
        "class": "sorceress",
        "ilvl-endless": 1340,
        "ilvl-aor": 1340,
        "lopang": True,
        "leapstones": False,
        "guildDonation": False,
        "rapport": False,
    },
    {
        "index": 10,
        "class": "glavier",
        "ilvl-endless": 1340,
        "ilvl-aor": 1340,
        "lopang": True,
        "leapstones": False,
        "guildDonation": False,
        "rapport": False,
    }
]
